export const projects = [
  {
    title: 'TikTok Clone',
    description: "TikTok Clone Application includes Google Auth, the ability to upload, publish, share, comment on, and like the videos, filtering by categories and search functionalities, profile pages, suggested accounts, custom responsive design, and much more.",
    image: '/images/01.jpeg',
    tags: ['React', 'Next', 'Sanity', 'Tailwind', 'Zustand'],
    source: 'https://tiktok-clone-alpha.vercel.app/',
    visit: 'https://github.com/btokmach/tiktok-clone',
    id: 0,
  },
  {
    title: 'Marvel information portal',
    description:"Marvel information portal. Application using ReactJS, Redux and Marvel Comics API. With the functionality to choose random character from Marvel API, searching a character by name, pagination and more.",
    image: '/images/02.jpeg',
    tags: ['React', 'Redux', 'Marvel Comics API'],
    source: 'https://marvel-bt.herokuapp.com/',
    visit: 'https://github.com/btokmach/marvel-app',
    id: 1,
  },
  {
    title: 'React Fitness Application',
    description: "Fitness Exercises App using two separate APIs. With the functionality to choose exercise categories and specific muscle groups, browse more than one thousand exercises with practical examples, pagination, exercise details, pull related videos from youtube, display similar exercises, and much more.",
    image: '/images/03.jpeg',
    tags: ['React', 'Material UI', 'RapidAPI'],
    source: 'https://bt-gym-exercises.netlify.app/',
    visit: 'https://github.com/btokmach/gym_exercises',
    id: 2,
  },
  {
    title: 'Photo Portfolio',
    description: "Responsive Next JS Website Using Tailwind CSS.",
    image: '/images/04.jpeg',
    tags: ['React', 'Next', 'Tailwind'],
    source: 'https://github.com/btokmach',
    visit: 'https://github.com/btokmach/photo-portfolio',
    id: 3,
  },
  {
    title: 'Weather app',
    description: "Weather application using ReactJS and OpenWeather API with places autocomplete.",
    image: '/images/05.jpeg',
    tags: ['React', 'RapidApi', 'OpenWeather API'],
    source: 'https://github.com/btokmach',
    visit: 'https://github.com/btokmach/react-weather-app',
    id: 4,
  },
  {
    title: 'Full Stack E-Commerce Application',
    description: "Full Stack Ecommerce application with modern design, animations, the ability to add and edit products on the go using a CMS and all advanced cart functionalities.",
    image: '/images/06.jpeg',
    tags: ['React', 'Next', 'Sanity'],
    source: 'https://github.com/btokmach',
    visit: 'https://github.com/btokmach/ecommerce-app',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2018, text: 'Worked as a Junior SEO Specialist', },
  { year: 2019, text: 'Worked as a Middle SEO Specialist in Product Company', },
  { year: 2020, text: 'Worked as a SEO Specialist with freelance projects and consulting', },
  { year: 2021, text: 'Started my journey in Web Development', },
  { year: 2022, text: 'Open to new career opportunities in Web Development', },
];